queue_rules:
  - name: default
    merge_conditions: []

pull_request_rules:
  - name: merge and delete head
    conditions:
      - label=shipit
    actions:
      queue:
        name: default
      delete_head_branch:
